# Generated by Django 5.0.3 on 2024-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_weekstatus_unique_together_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
    ]
