# Generated by Django 5.0.3 on 2024-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg', null=True),
        ),
    ]
