# Generated by Django 5.0.3 on 2024-03-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_course_price_coursecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomment',
            name='user',
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='student',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
            preserve_default=False,
        ),
    ]
