# Generated by Django 5.0.3 on 2024-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_achievement_achievement_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/Default_pfp.svg', upload_to='profile_pics'),
        ),
    ]
