# Generated by Django 5.0.1 on 2024-04-19 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_courseweek_week_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='base.courseweek'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
