# Generated by Django 5.0.1 on 2024-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_coursematerial_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(default='Material Example', max_length=200),
            preserve_default=False,
        ),
    ]
