# Generated by Django 5.0.1 on 2024-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_coursematerial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='time_to_complete',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
