# Generated by Django 5.0.1 on 2024-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_quizgrade_total_marks_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
