# Generated by Django 5.0.1 on 2024-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
