# Generated by Django 5.0.1 on 2024-05-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_resource_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('QNS', 'Questions'), ('SOL', 'Solutions')], default='Questions', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='socials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.socials'),
        ),
    ]
